#ifndef OSLIB_IO_EVENTS_H_
#define OSLIB_IO_EVENTS_H_

enum IOEvent {
    JOYSTICK_UP,
    JOYSTICK_DOWN,
    JOYSTICK_LEFT,
    JOYSTICK_RIGHT,
    JOYSTICK_FIRE,
    JOYSTICK_LONG_PRESS,
    WEBSOCKET_IN // wifi
};

#endif
